
try{//normal code//
If(a===0)
throw"user not found"//wildirect to catch//
}catch(err)
{
console.log(err)
} 
finally{//both not working//
    
}